/**
 * Build for the renter frontend.
 *
 * Three jobs, in order:
 *
 * 1. **Copy the real artifact.** `RentalManager.json` is read from
 *    `packages/abi` (or `RENTAL_MANAGER_ABI_PATH`) and written next to the app
 *    so the browser can fetch it. It is copied, never written by hand — the
 *    artifact is generated by Role 2, and a hand-built copy would be exactly the
 *    second source of truth the repo forbids.
 * 2. **Bundle the renter modules** with esbuild, targeting modern evergreen
 *    browsers, with the same four chain/shared module paths that
 *    `tsconfig.json` maps.
 * 3. **Fail loudly on a missing artifact**, because a page that renders without
 *    the contract interface would offer buttons that can only revert.
 *
 * Run `npm run build` from `apps/web` (or `npm run verify` for typecheck,
 * tests, then build).
 */

import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build, context } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../..');

/** Where the artifact comes from: an explicit path, or the pinned ABI package. */
const abiSource =
  process.env.RENTAL_MANAGER_ABI_PATH
    ? resolve(process.env.RENTAL_MANAGER_ABI_PATH)
    : join(repoRoot, 'packages', 'abi', 'RentalManager.json');

if (!existsSync(abiSource)) {
  console.error(
    `\n[RentalManager.json] not found at:\n  ${abiSource}\n\n` +
      'The renter cannot build a transaction without the exported ABI, so this ' +
      'build stops here rather than shipping a page whose buttons revert.\n\n' +
      'Role 2 owns generation of this artifact. When it lands, re-run:\n' +
      '  npm run build --workspace @archcore/web\n',
  );
  process.exit(1);
}

// The statically imported browser ABI and the published JSON must be identical.
// An alternate path may locate the same generated artifact, not another interface.
const canonicalAbi = join(repoRoot, 'packages', 'abi', 'RentalManager.json');
if (!readFileSync(abiSource).equals(readFileSync(canonicalAbi))) {
  throw new Error('Web ABI override differs from the current source-generated artifact.');
}

function publicOrigin(value, variable) {
  let url;
  try { url = new URL(value); } catch { throw new Error(`${variable} must be a public HTTP(S) origin.`); }
  if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password ||
      url.pathname !== '/' || url.search || url.hash) {
    // Never print the rejected value: it may contain an operator credential.
    throw new Error(`${variable} must be credential-free, with no path, query, or fragment.`);
  }
  return url.origin;
}
const browserRpc = publicOrigin(process.env.NEXT_PUBLIC_RH_RPC_URL || 'https://rpc.testnet.chain.robinhood.com', 'NEXT_PUBLIC_RH_RPC_URL');
const browserExplorer = publicOrigin(process.env.NEXT_PUBLIC_RH_EXPLORER_URL || 'https://explorer.testnet.chain.robinhood.com', 'NEXT_PUBLIC_RH_EXPLORER_URL');

// The artifact must parse, and must carry all 11 required P0 methods per ledger §2, before it is
// served to the browser. A renamed method silently disables one of the renter's
// flows, and the paste into the browser is far too late to find out.
let abi;
try {
  abi = JSON.parse(String(readFileSync(abiSource)));
} catch (error) {
  console.error(`\n[${abiSource}] is not valid JSON: ${String(error)}\n`);
  process.exit(1);
}

const entries = Array.isArray(abi) ? abi : Array.isArray(abi?.abi) ? abi.abi : null;
if (!entries) {
  console.error(
    `\n[${abiSource}] is neither an array nor an object with an "abi" array. ` +
      'See packages/abi/README.md for the accepted shapes.\n',
  );
  process.exit(1);
}

// Every method the renter's pages call, validated against the 11 required P0 methods
// defined by INTERFACE_CONTRACTS.md §2. Production reads are paymentToken, planCount,
// getPlan, getNode, getListing, getRental, and activeRentalForNode. Production writes
// are rent, startRental, cancelExpiredReservation, and settleAfterExpiry.
// Note: activeRentalForNode is the canonical production selector; nodeIsRented is an
// internal TypeScript wrapper helper only. A name missing here causes the build to fail closed.
const REQUIRED = [
  'paymentToken',
  'planCount',
  'getPlan',
  'getNode',
  'getListing',
  'getRental',
  'activeRentalForNode',
  'rent',
  'startRental',
  'cancelExpiredReservation',
  'settleAfterExpiry',
];
const present = new Set(
  entries.filter((e) => e && e.type === 'function' && typeof e.name === 'string').map((e) => e.name),
);
const missing = REQUIRED.filter((name) => !present.has(name));
if (missing.length > 0) {
  console.error(
    `\n[${abiSource}] is missing the methods the renter needs: ${missing.join(', ')}\n\n` +
      'Both the reads and the writes come from this artifact, so an incomplete ' +
      'ABI would ship a page that can only revert.\n',
  );
  process.exit(1);
}

const outDir = join(here, 'public');
mkdirSync(outDir, { recursive: true });

// 1. the artifact, copied verbatim for the browser to fetch
const abiTarget = join(outDir, 'rental-manager.json');
copyFileSync(abiSource, abiTarget);
console.log(`[abi] copied ${abiSource} -> ${abiTarget}`);

// 2. the renter bundle
const browserAbiPlugin = {
  name: 'generated-browser-abi',
  setup(b) {
    b.onResolve({ filter: /^\.\/abi(?:\.js)?$/ }, (args) => {
      if (args.importer.includes('/packages/chain/')) {
        return { path: resolve(repoRoot, 'packages/chain/src/abi.browser.ts') };
      }
    });
  },
};

const buildOptions = {
  define: {
    ARCHCORE_WEB_RPC_URL: JSON.stringify(browserRpc),
    ARCHCORE_WEB_EXPLORER_URL: JSON.stringify(browserExplorer),
  },
  entryPoints: [join(here, 'src', 'main.ts')],
  outfile: join(outDir, 'dist', 'app.js'),
  bundle: true,
  format: 'iife',
  target: ['chrome120', 'firefox120', 'safari17'],
  platform: 'browser',
  minify: true,
  sourcemap: true,
  legalComments: 'none',
  logLevel: 'info',
  plugins: [browserAbiPlugin],
  alias: {
    '@archcore/chain': resolve(repoRoot, 'packages/chain/dist/index.js'),
    '@archcore/chain/decode': resolve(repoRoot, 'packages/chain/dist/decode.js'),
    '@archcore/chain/status': resolve(repoRoot, 'packages/chain/dist/status.js'),
    '@archcore/chain/rentalManagerClient': resolve(repoRoot, 'packages/chain/dist/rentalManagerClient.js'),
    '@archcore/shared': resolve(repoRoot, 'packages/shared/dist/index.js'),
  },
};

if (process.argv.includes('--watch')) {
  const ctx = await context(buildOptions);
  await ctx.watch();
  console.log('[dev] Watching source. Open the local Agent origin after starting agent:dev.');
} else {
  const result = await build({ ...buildOptions, metafile: true });
  const forbidden = Object.keys(result.metafile.inputs).filter((name) => /node:|\/abi\.ts$/.test(name));
  if (forbidden.length) throw new Error('Node ABI loader unexpectedly reached the browser bundle.');
}

console.log('[build] wrote public/dist/app.js from src/main.ts');
